spring:
  application:
    name: coreflow

  main:
    allow-circular-references: true
    
  jpa:
    hibernate:
      ddl-auto: create-drop  # create-drop, upload
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 3600  # 1 hour in seconds
  refresh:
    expiration: 86400  # 24 hours in seconds
