server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coreflow
    username: postgres
    password: 1234567890

    driver-class-name: org.postgresql.Driver

upload:
  path: uploads

app:
  ocr:
    tesseract:
      cli: C:\\Program Files\\Tesseract-OCR\\tesseract.exe
