server:
  port: ${DEV_SERVER_PORT:8080}

spring:
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

upload:
  path: ${DEV_UPLOAD_PATH:uploads}

app:
  ocr:
    tesseract:
      cli: ${DEV_TESSERACT_CLI:C:\\Program Files\\Tesseract-OCR\\tesseract.exe}
