server:
  address: ${PROD_SERVER_ADDRESS:0.0.0.0}
  port: ${PROD_SERVER_PORT:8085}

spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}


upload:
  path: ${PROD_UPLOAD_PATH:/uploads}

app:
  ocr:
    tesseract:
      cli: ${PROD_TESSERACT_CLI:tesseract}
