server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coreflow_dev
    username: postgres
    password: root@IET25

    driver-class-name: org.postgresql.Driver

upload:
  path: uploads

app:
  ocr:
    tesseract:
      cli: C:\\Program Files\\Tesseract-OCR\\tesseract.exe
