spring:
  application:
    name: coreflow

  main:
    allow-circular-references: true
    
  jpa:
    hibernate:
      ddl-auto: update  # create-drop, update, create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 3600  # 1 hour in seconds
  refresh:
    expiration: 86400  # 24 hours in seconds

logging:
  level:
    com.astraval.coreflow: INFO

app:
  file:
    upload:
      item-images: uploads/item_img
      payment-proofs: uploads/payment_proof

firebase:
  enabled: ${FIREBASE_ENABLED:false}
  project-id: ${FIREBASE_PROJECT_ID:}
  credentials:
    file-path: ${FIREBASE_CREDENTIALS_FILE_PATH:}
    json: ${FIREBASE_CREDENTIALS_JSON:}
